Fix bookmarklet generator
There are bookmarklet generator, but it's not working:

```
curl http://remot.io/123/bm.js
ReferenceError: /opt/run/snapshot/package/views/bookmarklet.ejs:9
    7| var remot = {
    8| 	io: {
 >> 9| 		uid : '<%- id %>'
    10| 	}
    11| }
    12| (function() {
```

This commit is fixing typo (`id` instead of `uid`)